# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'img_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from itertools import count
from PyQt5 import QtCore, QtGui, QtWidgets
import glob
from numpy import sort

img_list = []
img_formats = ('*.jpg', '*.jpeg', '*.png')
for img in img_formats:
    imgs = glob.glob('img/'+ img)
    img_list.append(imgs)

sort(img_list)
# print(img_list)

non_empty_img_list = []

for i in img_list:
    if len(i)!=0:
        non_empty_img_list.append(i)

# print('non_empty_img_list: ', non_empty_img_list)

final_img_list = []
if len(non_empty_img_list)>0:
    for j in range(len(non_empty_img_list)):
        final_img_list = non_empty_img_list[j] + final_img_list

# print('final_img_list: ', final_img_list)

count = 0
total_img = len(final_img_list) - 1


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(-4, 6, 641, 381))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("img/WhatsApp Image 2022-07-05 at 2.46.28 PM.jpeg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(-2, 394, 311, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 394, 321, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.clicked_button1)
        self.pushButton_2.clicked.connect(self.clicked_button2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Image1"))
        self.pushButton_2.setText(_translate("MainWindow", "Image2"))

    def clicked_button1(self):
        global count
        if count==0:
            count = total_img
        else:
            count = count - 1
        self.photo.setPixmap(QtGui.QPixmap(final_img_list[count]))
    def clicked_button2(self):
        global count
        if count==total_img:
            count = 0
        else:
            count = count + 1
        self.photo.setPixmap(QtGui.QPixmap(final_img_list[count]))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
